### ISSUE TITLE
Visibility einer Figur ohne Funktion

### ISSUE THREAD

**Issue by UnrealCatze** [UnrealCatze/FigureDatabase#10]
zufällig, weil ich mal einen Figur nur für mich als Admin freischalten wollte hatte ich diese funktion gewählt aber gemerkt das die gar nicht funktioniert ... vor langer zeit hatte sie aber aber da auch die Core Files ständig geändert werden leigt es vielleicht auch daran. Jedenfalls gehts nicht. 

Wäre aber nicht schlecht diese funktion wieder zu haben ,... eventuellnoch mit einen Hinweis (sternchen oder so) in den panels damit man sieht aha .. diese Figur sehe nur ich ... 

Da fällt mir aber gerade ein .... was ist wenn ich nachträglich eine Figur "unsichtbar" mache und die hat jemand in seiner Sammlung? Dann wäre die dort weg

![unbenannt](https://cloud.githubusercontent.com/assets/22166864/20917461/f9832a64-bb91-11e6-8906-a891c0d038c5.JPG)

**Comment by DavidGuetl** [comment]
Funktioniert die Sichtbarkeit zumindest in der neuen Ansicht ? Ja oder?

Betreffend der Anzeige .. jenachdem wie es programmiert wurde, aber im Normalfall sollte sie verschwinden.

**Comment by UnrealCatze** [comment]
Nein .... wenn ich als gast da bin sehe ich die Figur immer noch obwohl ich die auf Superadmin gestellt habe

**Comment by UnrealCatze** [comment]
geht m it den neuen Core dateinen wieder . ....closed
