### ISSUE TITLE
Fehler: bei infuse werden die Navi-Links nicht mehr angelegt

### ISSUE THREAD

**Issue by UnrealCatze** [UnrealCatze/FigureDatabase#13]
scheint aber an der core zu leigen weil es ging füher. Ist nicht ganz so schlimm weil man die auch per hand machen kann aber eigentlich sollten sie beim infusionieren mit angelegt werden. In der neuen Version von PHPF9 wirden die Links weder in der Kopf oder in der seitennavi angezeigt.

hier der Auszug aus der infusion.php
habs auch mal in UK gepostet: https://github.com/php-fusion/PHP-Fusion/issues/1191
```

// always find and loop ALL languages
$enabled_languages = makefilelist(LOCALE, ".|..", TRUE, "folders");
// Create a link for all installed languages
if (!empty($enabled_languages)) {
	foreach($enabled_languages as $language) {
		include LOCALE.$language."/setup.php";
		// add new language records
		$mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, 		link_language) VALUES ('".$locale['INF_TITLE']."', 'infusions/figurelib/figures.php', '0', '2', '0', '2', '".$language."')";
		$mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_language) VALUES ('".$locale['mycollection']."', 'infusions/figurelib/mycollection.php', ".USER_LEVEL_MEMBER.", '2', '0', '3', '".$language."')";				
		$mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_language) VALUES ('".$locale['figure_521']."', 'infusions/figurelib/submit.php?stype=f', ".USER_LEVEL_MEMBER.", '2', '0', '4', '".$language."')";
		
		//$locale['figure_533'] = "Figure Stats";
		$mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_language) VALUES ('".$locale['figure_533']."', 'infusions/figurelib/panels/figurelib_stats_panel.php', '0', '2', '0', '5', '".$language."')";
				
		// drop deprecated language records
		$mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/figures.php' AND link_language='".$language."'";
		$mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/mycollection.php' AND link_language='".$language."'";
		$mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/submit.php?stype=f' AND link_language='".$language."'";
		$mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/panels/figurelib_stats_panel.php' AND link_language='".$language."'";
		$mlt_deldbrow[$language][] = DB_FIGURE_CATS." WHERE figure_cat_language='".$language."'";
	}
} else {
		$inf_insertdbrow[] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_language) VALUES('".$locale['setup_3307']."', 'infusions/figurelib/figures.php', '0', '2', '0', '2', '".LANGUAGE."')";
}
/*
```

**Comment by DavidGuetl** [comment]
Evtl eine Fehlermeldung?

**Comment by UnrealCatze** [comment]
schau mal unter dem englischen link https://github.com/php-fusion/PHP-Fusion/issues/1188#issuecomment-265111560

habe settings eingebaut in die infusion.php aber es geht trotzdem nicht

**Comment by DavidGuetl** [comment]
Versuche mal bei USER_LEVEL_MEMBER die ". Und ." Zu entfernen oder es in ' ' zu setzten, also '".USER_LEVEL_MEMBER."'

**Comment by UnrealCatze** [comment]
es ging ja vorher aber ich kanns probieren

**Comment by UnrealCatze** [comment]
habe mal gerade bei der anderen Infusion (Blog) geschaut 

da ist es aber auch so: 
} else {
    $inf_insertdbrow[] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status, link_language) VALUES('".$locale['setup_3055']."', 'infusions/blog/blog.php', '0', '2', '0', '2', '1', '".LANGUAGE."')";
    $inf_insertdbrow[] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status, link_language) VALUES ('".$locale['setup_3317']."', 'submit.php?stype=b', ".USER_LEVEL_MEMBER.", '1', '0', '14', '1', '".LANGUAGE."')";

**Comment by UnrealCatze** [comment]
eiss woran es leigen könnte die haben das geändert es gibt jetzt

link_status,

das war vorher nicht :O

**Comment by DavidGuetl** [comment]
Ok dass könnte es sein aber glaub eher nicht aber versuche es mal :-)

**Comment by UnrealCatze** [comment]
also ich habe alles umgebaut aber es kommt nichts --leigt an der theme?

> // always find and loop ALL languages
> $enabled_languages = makefilelist(LOCALE, ".|..", TRUE, "folders");
> // Create a link for all installed languages
> if (!empty($enabled_languages)) {
>     foreach ($enabled_languages as $language) {
> 
>         $locale = fusion_get_locale('', LOCALE.$language."/setup.php");
> 		
> 		// add new language records
> 		$mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status, link_language) VALUES ('".$locale['INF_TITLE']."', 'infusions/figurelib/figures.php', '0', '0', '2', '0', '2', '".$language."')";
> 	
> 		
> 		$mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status,  link_language) VALUES ('".$locale['mycollection']."', 'infusions/figurelib/mycollection.php', ".USER_LEVEL_MEMBER.", '0', '2', '0', '3', '".$language."')";				
> 		
> 		$mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status, link_language) VALUES ('".$locale['figure_521']."', 'infusions/figurelib/submit.php', ".USER_LEVEL_MEMBER.", '0', '2', '0', '4', '".$language."')";
> 		
> 		//$locale['figure_533'] = "Figure Stats";
> 		$mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status, link_language) VALUES ('".$locale['figure_533']."', 'infusions/figurelib/panels/figurelib_stats_panel.php', '0', '0', '2', '0', '5', '".$language."')";
> 								
> 		// drop deprecated language records
> 		$mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/figures.php' AND link_language='".$language."'";
> 		$mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/mycollection.php' AND link_language='".$language."'";
> 		$mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/submit.php?stype=f' AND link_language='".$language."'";
> 		$mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/panels/figurelib_stats_panel.php' AND link_language='".$language."'";
> 		$mlt_deldbrow[$language][] = DB_FIGURE_CATS." WHERE figure_cat_language='".$language."'";
> 	}
> } else {
> 		$inf_insertdbrow[] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status, link_language) VALUES('".$locale['setup_3307']."', 'infusions/figurelib/figures.php', ".USER_LEVEL_MEMBER.", '0', '2', '0', '2', '".LANGUAGE."')";
> 		
> }

**Comment by UnrealCatze** [comment]
ne leigt auch nicht an der Theme ... hmnn weiter suchen
ich kann kein fehler mehr finden ... ich denke ich poste das mal ins engische

**Comment by UnrealCatze** [comment]
https://github.com/php-fusion/PHP-Fusion/issues/1192

**Comment by DavidGuetl** [comment]
Mir fällt Grad auf du Speicherst einen Datensatz weniger als wie Spalten angegeben.

Eventuell liegt es daran?!.

**Comment by UnrealCatze** [comment]
habs gelöst

**Comment by UnrealCatze** [comment]
komisch gerade nochmal probiert .. jetzt gehts wieder nicht

```
// always find and loop ALL languages
$enabled_languages = makefilelist(LOCALE, ".|..", TRUE, "folders");
// Create a link for all installed languages
if (!empty($enabled_languages)) {
	foreach($enabled_languages as $language) {
		include LOCALE.$language."/setup.php";
		// add new language records
		$mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status,	link_language) VALUES ('".$locale['INF_TITLE']."', 'infusions/figurelib/figures.php', '0', '2', '0', '2', '1', '".$language."')";
		$mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status, link_language) VALUES ('".$locale['mycollection']."', 'infusions/figurelib/mycollection.php', ".USER_LEVEL_MEMBER.", '2', '0', '3', '1', '".$language."')";				
		$mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status, link_language) VALUES ('".$locale['figure_521']."', 'infusions/figurelib/submit.php?stype=f', ".USER_LEVEL_MEMBER.", '2', '0', '4', '1', '".$language."')";
		
		//$locale['figure_533'] = "Figure Stats";
		$mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status, link_language) VALUES ('".$locale['figure_533']."', 'infusions/figurelib/panels/figurelib_stats_panel.php', '0', '2', '0', '5', '1', '".$language."')";
				
		// drop deprecated language records
		$mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/figures.php' AND link_language='".$language."'";
		$mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/mycollection.php' AND link_language='".$language."'";
		$mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/submit.php?stype=f' AND link_language='".$language."'";
		$mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/panels/figurelib_stats_panel.php' AND link_language='".$language."'";
		$mlt_deldbrow[$language][] = DB_FIGURE_CATS." WHERE figure_cat_language='".$language."'";
	}
} else {
		$inf_insertdbrow[] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status, link_language) VALUES('".$locale['setup_3307']."', 'infusions/figurelib/figures.php', '0', '2', '0', '2', '1', '".LANGUAGE."')";
}
```

**Comment by UnrealCatze** [comment]
habs jetzt so und jetzt gehts wieder einmal ... mal sehen ob später immer noch :)

```
> // always find and loop ALL languages
> $enabled_languages = makefilelist(LOCALE, ".|..", TRUE, "folders");
> // Create a link for all installed languages
> if (!empty($enabled_languages)) {
> 	foreach($enabled_languages as $language) {
> 		include LOCALE.$language."/setup.php";
> 		// add new language records
> 		$mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status,	link_language) VALUES ('".$locale['INF_TITLE']."', 'infusions/figurelib/figures.php', '0', '2', '0', '2', '1', '$language')";
> 					
> 		$mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status, link_language) VALUES ('".$locale['mycollection']."', 'infusions/figurelib/mycollection.php', ".USER_LEVEL_MEMBER.", '2', '0', '3', '1', '$language')";				
> 		$mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status, link_language) VALUES ('".$locale['figure_521']."', 'infusions/figurelib/submit.php?stype=f', ".USER_LEVEL_MEMBER.", '2', '0', '4', '1', '$language')";
> 		
> 		//$locale['figure_533'] = "Figure Stats";
> 		$mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status, link_language) VALUES ('".$locale['figure_533']."', 'infusions/figurelib/panels/figurelib_stats_panel.php', '0', '2', '0', '5', '1', '$language')";
> 				
> 		// drop deprecated language records
> 		$mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/figures.php' AND link_language='$language'";
> 		$mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/mycollection.php' AND link_language='$language'";
> 		$mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/submit.php' AND link_language='$language'";
> 		$mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/panels/figurelib_stats_panel.php' AND link_language='$language'";
> 		$mlt_deldbrow[$language][] = DB_FIGURE_CATS." WHERE figure_cat_language='$language'";
> 	}
> } else {
> 		$inf_insertdbrow[] = DB_SITE_LINKS." (link_name, link_url, link_visibility, link_position, link_window, link_order, link_status, link_language) VALUES('".$locale['setup_3307']."', 'infusions/figurelib/figures.php', '0', '2', '0', '2', '1', '$language')";
> }
```

**Comment by UnrealCatze** [comment]
geht wieder
