### ISSUE TITLE
INFO globale ersetzt

### ISSUE THREAD

**Issue by UnrealCatze** [UnrealCatze/FigureDatabase#14]
habe alle global = $userdata usw.

durch diese ersetzt

$settings = fusion_get_settings();
$aidlink = fusion_get_aidlink();
$userdata = fusion_get_userdata();
$locale = fusion_get_locale();

**Comment by DavidGuetl** [comment]
Ok Ja, bei den neuen Bereichen im Admin und dergleichen passe ich es ja gleich nach und nach an :-)

**Comment by UnrealCatze** [comment]
neue files habe ich dir eben geschickt ... ich mache das hier zu :)
