### ISSUE TITLE
INFO: statistic panel gebaut :)

### ISSUE THREAD

**Issue by UnrealCatze** [UnrealCatze/FigureDatabase#21]
was hälst du davon? bersser als das an der Seite - live auf der /site1/ site

![ashampoo_snap_2016 12 08_20h08m47s_002_](https://cloud.githubusercontent.com/assets/22166864/21023776/42db39b2-bd82-11e6-9d39-986347385a04.jpg)

**Comment by UnrealCatze** [comment]
erst wollte ich das mit richtigen Bildern machen aber ich habe keine passenden gefunden
bunt hätte es eventuell besser ausgesehen :) 

![ashampoo_snap_2016 12 08_20h13m17s_003_](https://cloud.githubusercontent.com/assets/22166864/21023889/b6781214-bd82-11e6-9906-b73db5e9e1ba.jpg)

**Comment by DavidGuetl** [comment]
Magst einen Geheimtipp zu ca. 3000Bilder in 16x16px haben? Welche noch dazu hochwertige Qualität haben ;-) ?

**Comment by UnrealCatze** [comment]
hmnnn ich habe jetzt awesome icons genommen wie überall .. sollte mand abei bleiben?

**Comment by DavidGuetl** [comment]
Naja .. Ich sag mal so im Grossteil ja .. Aber bei Statistiken und so nehme ich selbst auch farbige.

**Comment by UnrealCatze** [comment]
na dann her ... aber absolut copyright free und die müssen auch gewerblich nutzbar sein ... bei werbung und affilate auf der seite verlässt mn den privateb bereich ... das zählt lauf deutschen recht zu gewerbe!

**Comment by DavidGuetl** [comment]
Was ich in Erinnerung habe steht in der Readmore man soll einen Link ins Impressum einfügen

http://p.yusukekamiyamane.com

Laut Lizenzbedingungen darf man es kommerziell verwenden.

**Comment by UnrealCatze** [comment]
.O dann lass ichs
