### ISSUE TITLE
INFO: infusion.php

### ISSUE THREAD

**Issue by UnrealCatze** [UnrealCatze/FigureDatabase#22]
habe die nochmal umgebaut und die Seitenlinks komplett neu geschrieben
jetzt gibts ein Tree-Menü
alles wie immer zu sehen live auf /site1/

![ashampoo_snap_2016 12 08_20h17m18s_004_](https://cloud.githubusercontent.com/assets/22166864/21024001/3f6d0368-bd83-11e6-8325-608b69b8617b.jpg)

**Comment by DavidGuetl** [comment]
Sieht aufjedenfall besser aus als Vorher - schön kompakt :-)

**Comment by UnrealCatze** [comment]
ich schicke dir später mal die aktuellen dateien
