### ISSUE TITLE
figurelib_latest_panel.ph -->  Use of undefined constant IMAGES_FIGURES - assumed 'IMAGES_FIGURES'

### ISSUE THREAD

**Issue by UnrealCatze** [UnrealCatze/FigureDatabase#23]
figurelib_latest_panel.php
/site1/home.php **
Line: 226

Severity : Run-time notices
Use of undefined constant IMAGES_FIGURES - assumed 'IMAGES_FIGURES'

> > in der infusion.db.php
> > if (!defined("DB_FIGURE_IMAGES")) {
> > 	define("DB_FIGURE_IMAGES", DB_PREFIX."figure_images");
> > }
> 
> // FOLDERS for Figures
> if (!defined("FIGURES")) {
>     define("FIGURES", INFUSIONS.$inf_folder."/images/figures/"); 
> }
> if (!defined("THUMBS_FIGURES")) {
>     define("THUMBS_FIGURES", INFUSIONS.$inf_folder."/images/figures/thumbs/");
> }

könnte das hier sein

> // Get correct Image
> 				if (dbcount("(figure_images_image_id)", DB_FIGURE_IMAGES, "figure_images_figure_id='".$data['figure_id']."'")) {
> 					$imageData = dbarray(dbquery("
> 						SELECT
> 							figure_images_image, figure_images_thumb
> 						FROM ".DB_FIGURE_IMAGES."
> 						WHERE figure_images_figure_id='".$data['figure_id']."' AND figure_images_image NOT LIKE '%default%'
> 						ORDER BY figure_images_toppic DESC
> 						LIMIT 0,1
> 					"));
> 					if ($imageData['figure_images_thumb'] && @file_exists(THUMBS_FIGURES.$imageData['figure_images_thumb'])) {
> 						$imageURL = THUMBS_FIGURES.$imageData['figure_images_thumb'];
> 					} elseif ($imageData['figure_images_image'] && @file_exists(IMAGES_FIGURES.$imageData['figure_images_image'])) {
> 						$imageURL = IMAGES_FIGURES.$imageData['figure_images_image'];
> 					} else {
> 						$imageURL = INFUSIONS."figurelib/images/default.png";
> 					}
> 				} else {
> 					$imageURL = INFUSIONS."figurelib/images/default.png";
> 				}

**Comment by UnrealCatze** [comment]
ICH HABE MAL IN ZEILE 226

IMAGES_FIGURES zu nur FIGURES da es die constante so ja nicht gab. Teheretisch wäre es sinnvoll die wirklich so zu nennen ... also IMAGES_FIGURES ... aber dann gehen andere scripptr nicht richtig

**Comment by DavidGuetl** [comment]
Erstelle fürs erste mal beide Konstanten . . Da wir eh alles überarbeiten können wir dass dann vereinfachen.

**Comment by UnrealCatze** [comment]
ok ich habe die dazugepackt .. erstmal closed
