### ISSUE TITLE
INFO . schau mal ob du einloggen kannst

### ISSUE THREAD

**Issue by UnrealCatze** [UnrealCatze/FigureDatabase#24]
auf derTestseite --> /test1/.....

habe die user wieder eingespielt

**Comment by DavidGuetl** [comment]
Funktioniert einwandfrei

**Comment by UnrealCatze** [comment]
das sind die neusten Code dateinen und auch die neusten Figurelib Dateinen .... 

wichtig das du auf der richtigen seit bis :) 

--> /site/ --> live
--> /site1/ --> test

**Comment by DavidGuetl** [comment]
Super passt ;-)
