### ISSUE TITLE
Fehler: Social Sharing geht wieder nicht

### ISSUE THREAD

**Issue by UnrealCatze** [UnrealCatze/FigureDatabase#25]
leigts an den Core dateien? Geht wieder nicht kommt seitenlogo und Beschreibung

**Comment by DavidGuetl** [comment]
In den Einstellungen auch die des Systems deaktiviert?

**Comment by UnrealCatze** [comment]
ja das ist ja mein problem

**Comment by UnrealCatze** [comment]
geht nicht mehr :(

**Comment by UnrealCatze** [comment]
auch wenn ich anschalte gehts nicht :( OMGGGGGGGGGGGGG

**Comment by DavidGuetl** [comment]
Verstehe ich nicht .. ging doch vorher auch ohne Probleme :o

**Comment by UnrealCatze** [comment]
ja aber da hatte ich nicht die aktuellen Core Dateien .. geht echt nicht mehr :(

**Comment by DavidGuetl** [comment]
Werde mir mal morgen die aktuelle Core laden und das testen. Sende mir bitte auch die aktuelle Figurelib für morgen.

**Comment by UnrealCatze** [comment]
https://github.com/php-fusion/PHP-Fusion/issues/1202

**Comment by UnrealCatze** [comment]
eben hats funktioniert . frasge mich nicht warum aber nicht über den Button sondernich habe den link direkt in FB eingefügt

**Comment by UnrealCatze** [comment]
bei der zwiten figur die ich dann probiert habe auf gleiche weise hats wieder nicht funktioniert

**Comment by DavidGuetl** [comment]
Verstehe ich nichr - alles komisch :o

**Comment by DavidGuetl** [comment]
Da Social Media komplett neu geschrieben ist, müssen wir auch hier neu schreiben.

**Comment by UnrealCatze** [comment]
ja einer meiner wichtigten Sachen... ohne dem bin ich aufgeschmissen.
