### ISSUE TITLE
Fehler: Suche - Notice 

### ISSUE THREAD

**Issue by UnrealCatze** [UnrealCatze/FigureDatabase#27]
wenn ich auf der Startseite ganz oben etwas eingebe gehts beim ersten mal nicht .. es passiert nichts .. gebe ich das dann noch einmal ein kommt ne Fehlermeldung .. Ergebnisse kommen aber

sieh auch mein Kommenta weiter unten

![ashampoo_snap_2016 12 09_20h47m34s_003_](https://cloud.githubusercontent.com/assets/22166864/21062358/c5d18c6c-be50-11e6-879f-1077056f625d.jpg)

**Comment by UnrealCatze** [comment]
Die suche geht nicht mehr so wie früher .. die habve die search.php im root neu geschrieben wie ich gesehen habe

man kann auch nicht mehr nach hersterller suchern .. wenn ich versuche 	
HEROCROSS zu suchen zeigt es immer 0 obwohl mehrer Figuren da die den hersteller haben

**Comment by DavidGuetl** [comment]
Dass müsste ich mir mal ansehen .. komme ja zurzeit zu garnichts :o

**Comment by UnrealCatze** [comment]
ich lade gerade alles runter und mach dir ein paket mit allen neuen datéien.

**Comment by DavidGuetl** [comment]
Danke! :-)

**Comment by DavidGuetl** [comment]
Besteht der Fehler eig noch?
