### ISSUE TITLE
INFO Dateien

### ISSUE THREAD

**Issue by UnrealCatze** [UnrealCatze/FigureDatabase#29]
habe dir die dateien geschickt. Paar sachen die defintiv nicht benötigt weerden habe ich rausgelöscht. Auch die ganzen Bilder der Figuren weil 300 mb groß :) 
falls du noch was brauchst melde dich

**Comment by DavidGuetl** [comment]
Ok passt - Ja muss mir das eh mal installieren, aber da ich derzeit am Adminbereich arbeite, kommentiere ich hier auch ein wenig weniger ;)

**Comment by UnrealCatze** [comment]
hast du dir das schon gezogen gehabt? ich habe es vorhin wieder gelöscht OMG


Am 11.12.2016 um 20:30 schrieb David:

**Comment by DavidGuetl** [comment]
Jaja schon lange ;-)

**Comment by UnrealCatze** [comment]
gut :) hatte gerade leicht panik

hast du gesehen ich habe einen groben fehler endeeckt ... images lassen 
sich nicht wählen wenn man eingeloggt ist. Als gast geht es

ich habe ab 9 uhr wieder meinen Unreal Tournament Zocker Abend .. bin 
also nicht am programmieren hehehehehe

ich wünsch dir einen schönen Sonntag noch
Gruß Steffen



Am 11.12.2016 um 20:47 schrieb David:

**Comment by DavidGuetl** [comment]
Hehe na dann wünsche ich viel Spass, wie gesagt bei mir funktionieren die Bilder ;-)

Und dir auch noch einen schönen Abend ;-)

**Comment by UnrealCatze** [comment]
👍
