### ISSUE TITLE
Schwerer Fehler: Bilder Slider geht nicht mehr

### ISSUE THREAD

**Issue by UnrealCatze** [UnrealCatze/FigureDatabase#32]
erst gerade bemerkt .. der slider geht nicht wenn man mehrere Bilder hat .. man sieht  nur das erste bild immer rechts und links weiterspulen geht nicht mehr

**Comment by UnrealCatze** [comment]
nur wenn man eingeloggt ist? also gast funktioniert es

**Comment by UnrealCatze** [comment]
![ashampoo_snap_2016 12 11_20h42m23s_008_](https://cloud.githubusercontent.com/assets/22166864/21082753/30b28b7a-bfe2-11e6-9406-f4bff550969b.jpg)

**Comment by DavidGuetl** [comment]
Google Chrome, Windows 10 -> Figur: http://aliencollectors.com/site/infusions/figurelib/figures.php?figure_id=580 -> Kein Fehler als Gast/Admin .

**Comment by UnrealCatze** [comment]
bei mir gehts nicht .. site läd nur neu aber das Bild bleibt imer das gleiche. Aber nur wenn ich als Superamin eingeloggt bin als gast gehts

**Comment by UnrealCatze** [comment]
also als normaler eingeloggter user gehts aucxh .. eventuell leigt es am Peel Panel was ich installiert habe .. aber jetzt wird erstmal gezockt hehe :)

**Comment by DavidGuetl** [comment]
Glaube auch weil ich hab ja noch immer einen Admin Account und da gehts auch :-)
