### ISSUE TITLE
Fehler: Bild nur halbe Größe

### ISSUE THREAD

**Issue by UnrealCatze** [UnrealCatze/FigureDatabase#33]
![ashampoo_snap_2016 12 13_20h46m09s_001_](https://cloud.githubusercontent.com/assets/22166864/21156185/2755c01c-c175-11e6-874c-5373f30e85c6.jpg)

die bilder die hochlade sind alle so klein und werden nicht in kompletter höhe also genau so hoch wie die sliderbox angezeigt .. warum?

**Comment by DavidGuetl** [comment]
Vermute mal, weil das Bild zu klein ist ;) ?

**Comment by UnrealCatze** [comment]
nein eben nicht die sind 1500x2000 
ich weiss nicht woran das leigt ... an der thumbnail erstelung? was muss ich in den settings bei PHPF einstellen GD1 oder 2? ich habe momentan dort GD2 .. leigt es daran?

**Comment by DavidGuetl** [comment]
Wie gross ist das Bild und wie sehen die Einstellungen in der Figurrlib aus?

**Comment by UnrealCatze** [comment]
1500 x1000 das erst zB in PHPF habe ich GD2 eingestellt

**Comment by UnrealCatze** [comment]
könnte von den neuen coe files kommen weil früher war das nicht. Veillecht haben die was am java oder am Bootstrap gemacht

**Comment by UnrealCatze** [comment]
also es leigt am Bootstrap theme. Aber  ... die Bilder sind bei allen Figuren kleiner als vorher ... also liegts an was anderes.

**Comment by UnrealCatze** [comment]
es liegt daran hier:

das
`<div id="myCarousel" class="carousel slide" data-ride="carousel" style="height: 500px !important; overflow: hidden;">`
zu das und dann gehts wieder
`<div id="myCarousel" class="carousel slide" data-ride="carousel" style="height: 500px overflow: hidden;">`

**Comment by DavidGuetl** [comment]
Oh Ok, na wichtig ist daas es geht :-)
