### ISSUE TITLE
BRAUCHE MAL DRINGEND HILFE EINEN VARIABLE EINZUBINDEN

### ISSUE THREAD

**Issue by UnrealCatze** [UnrealCatze/FigureDatabase#35]
versuche gerade einen Affilate Link zu genreiren und diesen einzubinden
ich möchte die variable in diesen code "einsetzen" = $asin

ich habe zig versionen probiert .. geht nicht .. wenn ich ein echo mache kommt die asin also ist die variable defintiv vorhanden aber 

```
					<!-- Amazon DE -->
					<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 text-center">
						<?php
						if ($info['figure']['affiliates']['amazon-de']) {
							
						 $info['figure']['affiliates']['amazon-de'] = $asin; 	
						?>
							
<iframe style="width:120px;height:240px;"marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-eu.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=DE&source=ac&ref=tf_til&ad_type=product_link&tracking_id=wwwaliencolle-21&marketplace=amazon&region=DE&placement=<?php= $asin;?>&asins=<?php= $asin;?>&linkId=&show_border=true&link_opens_in_new_window=true"></iframe>
						  
						<?php
						  						
						  }
						  ?>
					</div>
```

**Comment by UnrealCatze** [comment]
PHP version geht auch nicht

```
					<!-- Amazon DE -->
					<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 text-center">
						<?php
						if ($info['figure']['affiliates']['amazon-de']) {
							
						 $info['figure']['affiliates']['amazon-de'] = $asin; 	
													
echo "<iframe style='width:120px;height:240px;'marginwidth='0' marginheight='0' scrolling='no' frameborder='0' src='//ws-eu.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=DE&source=ac&ref=tf_til&ad_type=product_link&tracking_id=wwwaliencolle-21&marketplace=amazon&region=DE&placement=".$asin."&asins=".$asin."&linkId=&show_border=true&link_opens_in_new_window=true'></iframe>";
						  							
						  }
						  ?>
					</div>
```

**Comment by DavidGuetl** [comment]
Lol .. dass ist aber jetzt ein Zufall .. wollte dir gerade auf die E-Mails antworten *hihi*.

Also sowie ich das verstehe, ist ja dieses Widget immer das gleiche (auch bei Sprachen gesehen) nur dass es immer eine andere URL ist oder?

Falls Ja, würde ich an deiner Stelle vorschlagen, du speicherst einfach im Adminbereich bei einem Amazon-Link den Teil von src="xxx" ab (also nur die Url, symbolisch hier eben die xxx).

Und einbinden würde ich das ganze so:
```
<!-- Amazon DE -->
					<div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 text-center">
						<?php if ($info['figure']['affiliates']['amazon-de']) { ?>
						<iframe style="width: 120px; height: 240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="<?= $info['figure']['affiliates']['amazon-de']; ?>"></iframe>
						<?php } ?>
					</div>
```

Die Variable denke ich funktioniert nicht, da du diese falsch zuweißt.
Zurzeit weißt du so zu: 
Variable mit Wert = leere Variable

Richtig wäre aber:
leere Variable = Variable mit Wert, sprich
$asign = $info['figure']['affiliates']['amazon-de'];

**Comment by UnrealCatze** [comment]
hmmm kommt nichts was ist falsch??

                     
                     <div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 
text-center">
                         <?php
                         if ($info['figure']['affiliates']['amazon-de']) {

                          $asin = 
$info['figure']['affiliates']['amazon-de'];

echo "<iframe style='width:120px;height:240px;marginwidth='0' 
marginheight='0' scrolling='no' frameborder='0' 
src='//ws-eu.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=DE&source=ac&ref=tf_til&ad_type=product_link&tracking_id=wwwaliencolle-21&marketplace=amazon&region=DE&placement=".$asin."&asins=".$asin."&linkId=&show_border=true&link_opens_in_new_window=true'></iframe>";

                           }
                           ?>
                     </div>



Am 30.12.2016 um 22:45 schrieb David:

**Comment by DavidGuetl** [comment]
Fehlt vor den // nicht noch ein http: ?

Andernfalls gibt es eine Live-Url wo du den Code testest?

**Comment by UnrealCatze** [comment]
ja hier treste ich aber es geht nicht wird gar nichts angezeigt.

ich will ja nur die ASIN im code ersetzen alles andere ist immer gleich

http://aliencollectors.com/site/infusions/figurelib/figures.php?figure_id=562



Am 30.12.2016 um 22:51 schrieb David:

**Comment by UnrealCatze** [comment]
das ist der code der auf der seite eingebaut werden soll


Markieren und kopieren Sie den HTML-Code unten, und fügen Sie ihn dann 
in den Code Ihrer Website ein.

<iframe style="width:120px;height:240px;" marginwidth="0" 
marginheight="0" scrolling="no" frameborder="0" 
src="//ws-eu.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=DE&source=ac&ref=tf_til&ad_type=product_link&tracking_id=wwwaliencolle-21&marketplace=amazon&region=DE&placement=B00U0ZGT1Y&asins=B00U0ZGT1Y&linkId=&show_border=true&link_opens_in_new_window=true">
</iframe>

prinzipiell kann der immer gleich bleiben bis auf das die ASIN 
ausgetauscht werden muss. Alles andere ist ja immer gleich. das habe ich 
rausgefunden indem ich mehrere links mal generiert habe und diese 
verglichen habe.



http gibt da nicht warum auch immer


Am 30.12.2016 um 22:51 schrieb David:

**Comment by DavidGuetl** [comment]
Irgendwas baust du da falsch ein, denn bei dir im Quellcode auf der Seite ist ein display: none !important; dabei, deshalb wird wsl. auch nichts angezeigt.

Poste mal deinen Code 1:1 ich passe den an.

**Comment by UnrealCatze** [comment]
vielen lieben dank !!!!!!!!

DAS IST DAS WAS EINGEBAUT HABE:


                     

                     <div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 
text-center">
                         <?php if 
($info['figure']['affiliates']['amazon-de']) { ?>
                         <?php $asin = 
$info['figure']['affiliates']['amazon-de'];  ?>

                         <iframe 
style='width:120px;height:240px;marginwidth='0' marginheight='0' 
scrolling='no' frameborder='0' 
src='//ws-eu.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=DE&source=ac&ref=tf_til&ad_type=product_link&tracking_id=wwwaliencolle-21&marketplace=amazon&region=DE&placement=<?= 
$asin;?>&asins=<?= 
$asin;?>&linkId=&show_border=true&link_opens_in_new_window=true'></iframe>

                         <?php } ?>
                     </div>

DIE ASIN IST DAS HIER --> B00U0ZGT1Y DIE SPEICHERE ICH IN DER VARIBALE 
"$asin" ab

AMAZON MÖCHTE DAS SO:

<iframe style="width:120px;height:240px;" marginwidth="0" 
marginheight="0" scrolling="no" frameborder="0" 
src="//ws-eu.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=DE&source=ac&ref=tf_til&ad_type=product_link&tracking_id=wwwaliencolle-21&marketplace=amazon&region=DE&placement=B00U0ZGT1Y&asins=B00U0ZGT1Y&linkId=&show_border=true&link_opens_in_new_window=true">
</iframe>


Am 30.12.2016 um 22:59 schrieb David:

**Comment by DavidGuetl** [comment]
Loool! Sorry!

Also habe es nochmals probiert - das Widget wird doch angezeigt.

Hast du eventuell auch sowie ich Adblock installiert? Falls Ja, dann geht das nicht.

**Comment by DavidGuetl** [comment]
![test](https://cloud.githubusercontent.com/assets/19527428/21573426/7bbb0cbc-cee4-11e6-941a-3d86b663e490.png)

**Comment by UnrealCatze** [comment]
siehst du es aktuell? ich nicht

**Comment by UnrealCatze** [comment]
im edge browser sehe ich es .. das ist mist ... was schlägstt du vor? Dann vewrfehlt es sein Ziel ... gibt einen andere Möglichkeit? Amazon bietet ja noch mehr Möglichkeiten in seiner API nur das sind für mich bömische Dörfer

**Comment by DavidGuetl** [comment]
Naja, da das Teil von Adblock blockiert wird - Weiterhin als Link Methode?

**Comment by UnrealCatze** [comment]
hätte ich gerne gemacht aber Amazon verbietet in seiner AGB das verwenden von eigenen Bildern (so wie ich die Flaggen hatte) -- könnte man alternativ ein Textlink einbelnenden der aber nur dann angezeigt wird wenn das andere nicht geht? nur textlinks seheh doch langweilig aus ... es soll ja die leute aniemieren dort drauf zu klicken :) das ist mein Ziel LOL

hier der Code für nur textlink:

`<a rel="nofollow" href="https://www.amazon.de/gp/product/B00U0ZGT1Y/ref=as_li_tl?ie=UTF8&camp=1638&creative=6742&creativeASIN=B00U0ZGT1Y&linkCode=as2&tag=wwwaliencolle-21">ALIENS - Power Loader P-5000 Deluxe Vehicle 27 cm</a><img src="http://ir-de.amazon-adsystem.com/e/ir?t=wwwaliencolle-21&l=as2&o=3&a=B00U0ZGT1Y" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />`

**Comment by DavidGuetl** [comment]
Amazon is doof .. 

Naja das Problem ist .. man müsste irgendwie erkennen, ob IFrames in Browser Einstellungen blockiert sind, oder durch Adblocker oder oder oder ...

Welche Einbindungsmethoden hat Amazon noch zur Auswahl?

**Comment by UnrealCatze** [comment]
Text oder 
Nur Bild
`
<a rel="nofollow" href="https://www.amazon.de/gp/product/B00U0ZGT1Y/ref=as_li_tl?ie=UTF8&camp=1638&creative=6742&creativeASIN=B00U0ZGT1Y&linkCode=as2&tag=wwwaliencolle-21"><img border="0" src="http://ws-eu.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B00U0ZGT1Y&Format=_SL110_&ID=AsinImage&MarketPlace=DE&ServiceVersion=20070822&WS=1&tag=wwwaliencolle-21" ></a><img src="http://ir-de.amazon-adsystem.com/e/ir?t=wwwaliencolle-21&l=as2&o=3&a=B00U0ZGT1Y" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />`

**Comment by DavidGuetl** [comment]
Ich würde es mal mit dem Bild versuchen? :)

**Comment by UnrealCatze** [comment]
gleiches problem Firefox zeigt nichts an ... Edge zeigt jetzt beide (habe mal beide gelassen)
scheisse was mache ich jetzt? wie machen das andere? das ist ja nichts was ich als erstes mache das haben Millionen von Webseiten .. wie machen die das? 

als HTML auslagern und includen?

**Comment by DavidGuetl** [comment]
Also ich habe es nun mit Chrome versucht, aktivierten Adblocker, sieht es so aus:
![test](https://cloud.githubusercontent.com/assets/19527428/21573637/330295a0-cee7-11e6-86ac-ab0678afa7cb.png)

Dann habe ich mir jetzt extra Firefox geladen (Version 50.xx) und es sieht so aus (ohne Adblock oder dergleichen):
![test](https://cloud.githubusercontent.com/assets/19527428/21573652/521a2854-cee7-11e6-8a61-edf5651c7e3a.png)

Und im Edge (ebenfalls frische Installation) so:
![test](https://cloud.githubusercontent.com/assets/19527428/21573670/8702ec7c-cee7-11e6-9d94-82d0648ea653.png)

**Comment by UnrealCatze** [comment]
also würde es prinziepell gehen aber wird geblockt je nachdem was der user eingestellt hat.  Ich sehe im Firefox überhaupt nix.  Im Edge sehe ich beides. Auf dem handy wird auch beides angezeigt. Also leigts am Firefox bei mir. 

ich muss jetzt alles umbauen weil wie erwähnt amazon nicht erlaubt eigenen Bilder zu nehmen:

ich könnte A - die Bilder lassen und dahinter einen textlink einbauen
ich könnte B - für jedes Land wo es die Figur gibt den entsprechenden Code einbauen also etwa so
die usnteren 4 wären dann in diesen Ländern nicht verfügbar. 
Sollte halt irgendwie schön aussehen.  Ich weiss nicht wie ich es anders machen könnte

![unbenannt](https://cloud.githubusercontent.com/assets/22166864/21573789/0b8d25d8-cee9-11e6-8323-d3d6e0434dcb.jpg)

**Comment by DavidGuetl** [comment]
Du könntest ja die User darauf hinweisen, dass Sie den Adblock deaktivieren, damit Sie die Kaufvorschläge einer Figur sehen? :-)

**Comment by UnrealCatze** [comment]
Aber wie machen das die anderen? Es gibt ja die Amazon API ... vielleicht muss man dann irgendwas anders machen ... weil dann dürften ja auch anderen seiten wo sowas ist mir auch nichts angezeigt werden ... wird aber.

hier mal als beispiel .. die haben das auch aber da wird ein Bild bzw ein Button angezeigt: http://www.bluray-disc.de/blu-ray-filme/super-8-steelbook-blu-ray-disc

oder hier noch krasser
https://www.bluray-dealz.de/amazon-de-angebot-des-tages-top-titel-in-4k-ultra-hd-z-b-ghostbusters-1-2-fuer-je-2297e-vsk/115019/

ich sehe alles dort

**Comment by UnrealCatze** [comment]
habe es so gemacht erstmal bis ich eine andere Lösung finde. Alle Länder wo ich keinen Link oder vertrag habe bekommen ihr eigenes selbstgemachtes Banner als Platzhalter (verlinken darf man ja nicht) und dort wo vorhanden wird der orginal Link angezeigt

![ashampoo_snap_2016 12 31_00h30m44s_007_](https://cloud.githubusercontent.com/assets/22166864/21574273/7ba1a612-cef0-11e6-82b6-84a7445ca0c0.jpg)

**Comment by UnrealCatze** [comment]
also geht nicht im Firefox ... das ist sh... weil 99 % aller die ich kenne diesen nutzen. Ich brauche da eine Lösung 

so siehts jetzt aus:
![ashampoo_snap_2016 12 31_02h09m35s_008_](https://cloud.githubusercontent.com/assets/22166864/21574965/34efa198-cefe-11e6-9356-00f05dc58322.jpg)

**Comment by DavidGuetl** [comment]
Schick aussehen tut es ja erstmal :-)

Welche Api gibt es da?
