### ISSUE TITLE
INFO: habe das ganze affiliate system umgebaut 

### ISSUE THREAD

**Issue by UnrealCatze** [UnrealCatze/FigureDatabase#39]
hat aber noch paar macken
zum testen habe ich die Alien King figur wieder genommen :) --> http://aliencollectors.com/site/infusions/figurelib/figures.php?figure_id=265

neu DB --> ebay
alle spalten von Affiliate umbenannt damit klar wird worum es sich handelt
die dateien classes, figure admin und figure details habe ich soweit umgebaut

das ganze sieht so aus

		figure_affiliate_various_1 VARCHAR(254) NOT NULL DEFAULT '',
		figure_affiliate_various_2 VARCHAR(254) NOT NULL DEFAULT '',
		figure_affiliate_various_3 VARCHAR(254) NOT NULL DEFAULT '',
		figure_affiliate_various_4 VARCHAR(254) NOT NULL DEFAULT '',
		figure_affiliate_various_5 VARCHAR(254) NOT NULL DEFAULT '',
		figure_affiliate_various_6 VARCHAR(254) NOT NULL DEFAULT '',
		figure_affiliate_various_7 VARCHAR(254) NOT NULL DEFAULT '',
		figure_affiliate_various_8 VARCHAR(254) NOT NULL DEFAULT '',
		figure_affiliate_various_9 VARCHAR(254) NOT NULL DEFAULT '',
		figure_affiliate_various_10 VARCHAR(254) NOT NULL DEFAULT '',
		
		figure_affiliate_ebay_1 VARCHAR(254) NOT NULL DEFAULT '',
		figure_affiliate_ebay_2 VARCHAR(254) NOT NULL DEFAULT '',
		figure_affiliate_ebay_3 VARCHAR(254) NOT NULL DEFAULT '',
		figure_affiliate_ebay_4 VARCHAR(254) NOT NULL DEFAULT '',
		figure_affiliate_ebay_5 VARCHAR(254) NOT NULL DEFAULT '',
		figure_affiliate_ebay_6 VARCHAR(254) NOT NULL DEFAULT '',
		figure_affiliate_ebay_7 VARCHAR(254) NOT NULL DEFAULT '',
		figure_affiliate_ebay_8 VARCHAR(254) NOT NULL DEFAULT '',
		figure_affiliate_ebay_9 VARCHAR(254) NOT NULL DEFAULT '',
		figure_affiliate_ebay_10 VARCHAR(254) NOT NULL DEFAULT '',
		
		figure_eshop VARCHAR(254) NOT NULL DEFAULT '',
		
		figure_amazon_de VARCHAR(254) NOT NULL DEFAULT '',
		figure_amazon_uk VARCHAR(254) NOT NULL DEFAULT '',
		figure_amazon_fr VARCHAR(254) NOT NULL DEFAULT '',
		figure_amazon_es VARCHAR(254) NOT NULL DEFAULT '',
		figure_amazon_it VARCHAR(254) NOT NULL DEFAULT '',
		figure_amazon_jp VARCHAR(254) NOT NULL DEFAULT '',
		figure_amazon_com VARCHAR(254) NOT NULL DEFAULT '',
		figure_amazon_ca VARCHAR(254) NOT NULL DEFAULT '',

**Comment by DavidGuetl** [comment]
Ok :-)
