### ISSUE TITLE
INFO

### ISSUE THREAD

**Issue by UnrealCatze** [UnrealCatze/FigureDatabase#5]
ich habe die infusion.php mal überarbeitet und alle spalten mit "sorting" und "parent" rausgehauen
parent sind nur noch bei Cats und Manufacturer ... bei allen anderen machts keinen Sinn dehalb sind die raus

habe auf dem Space /site1 
mal eine neue Installation mit den neusten Corefiles von PHPF9 drauf

**Comment by DavidGuetl** [comment]
Sehr gut ! ;-)
