### ISSUE TITLE
Figuren Views werden nicht mehr gezählt

### ISSUE THREAD

**Issue by UnrealCatze** [UnrealCatze/FigureDatabase#6]
ist mir eben aufgefallen das die nicht funktionieren

![ashampoo_snap_2016 12 05_21h46m11s_001_](https://cloud.githubusercontent.com/assets/22166864/20901750/47d3f8f0-bb34-11e6-9933-d6d81c0f4c60.jpg)

**Comment by UnrealCatze** [comment]
das hier war immer in der figures.php drin

	// Update Counter
	dbquery("UPDATE ".DB_FIGURE_ITEMS." SET figure_clickcount=figure_clickcount+1 WHERE figure_id='".intval($_GET['figure_id'])."'");

bei jeden Aufruf der Figur wurde der aktualisiert so das gezählt wurde wie oft einen Figur angeschaut wurde

**Comment by DavidGuetl** [comment]
Suche in der figures.class.php in ca. Zeile 360 folgendes:
```
                // Check if Figure exists
		if (dbrows($result)) {
			$data = dbarray($result);
		} else {
			redirect(BASEDIR."index.php");
		}
```

Darunter füge folgendes ein:
```
// Update Counter and correct "at the Moment"-View
dbquery("UPDATE ".DB_FIGURE_ITEMS." SET figure_clickcount=figure_clickcount+1 WHERE figure_id='".$this -> figureID."'");
$data['figure_clickcount']++;
```

**Comment by UnrealCatze** [comment]
geht danke :)
