### ISSUE TITLE
Discreption usw. werden nicht 1 zu 1 angezeigt - Formatierung falsch

### ISSUE THREAD

**Issue by UnrealCatze** [UnrealCatze/FigureDatabase#7]
so siehts im Editor aus
![ashampoo_snap_2016 12 05_22h24m18s_005_](https://cloud.githubusercontent.com/assets/22166864/20902931/b177dd9e-bb39-11e6-9646-0d9163fffc31.jpg)

so auf der seite dann ... ab da fehlen die Formatierungen und die links gehen nicht
![ashampoo_snap_2016 12 05_22h24m01s_004_](https://cloud.githubusercontent.com/assets/22166864/20902939/b5da19f6-bb39-11e6-85cd-a8785729234a.jpg)

				// Accessories and Description
				"accessories" => parse_textarea(strip_tags($data['figure_accessories'])),
				"description" => parse_textarea(strip_tags($data['figure_description'])),

**Comment by DavidGuetl** [comment]
Theoretisch sollte es nach entfernen von strip_tags ohne Probleme funktionieren ... Habe ich wohl einen Fehler gemacht :-o

**Comment by UnrealCatze** [comment]
habe anstatt parse_textarea nun nl2br drin

// Accessories and Description
				"accessories" => nl2br(strip_tags($data['figure_accessories'])),
				"description" => nl2br(strip_tags($data['figure_description'])),

scheint zu gehen

das wie du sagst geht auch
// Accessories and Description
				"accessories" => parse_textarea($data['figure_accessories']),
				"description" => parse_textarea($data['figure_description']),

**was ist besser????**

**Comment by DavidGuetl** [comment]
Naja strip_tags() entfernt normalerweise auch die ganzen Tags wie Bild, Link und dergleichen soweit ich nun informiert bin.

parse_textarea() ist aufjedenfall die richtige Lösung, wird von PHP-Fusion auch so genutzt. Wieso ich hier die strip_tags() eingebaut habe, ist mir derzeit auch nicht klar, wohl einfach nicht mitgedacht.

**Comment by UnrealCatze** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/22166864/20916664/2d5ec08c-bb8d-11e6-9e28-947360f35ea1.JPG)

habe das problem wenn ich einen Link inbaue wird diese zeile auch oben auf der seite angezeigt ... da ist irgendwas faul

![unbenannt](https://cloud.githubusercontent.com/assets/22166864/20916718/69a6bebe-bb8d-11e6-958c-be4fa8ddd6f0.JPG)

**Comment by DavidGuetl** [comment]
Suche in der figures.class.php:
`add_to_head("<meta property='og:description' content='".$masterArray['figure']['general']['description']."' />");`

Ersetzte durch:
`add_to_head("<meta property='og:description' content='".strip_tags($masterArray['figure']['general']['description'])."' />");`

Weiteres Suche:
`add_to_head("<meta name='twitter:description' content='".$masterArray['figure']['general']['description']."' />");`

Ersetzte durch:
`add_to_head("<meta name='twitter:description' content='".strip_tags($masterArray['figure']['general']['description'])."' />");`

Code ist ca. bei Zeile 625.

**Comment by UnrealCatze** [comment]
geil funzt :) super dankeschön 👍
